#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Sep 13 14:53:51 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.9.1.zip
enableShaders=true
